language: R
cache: packages
latex: false


matrix:
  include:
    - r: release
    - r: devel
    # - os: osx
    #   fortran: false

warnings_are_errors: false

r_packages:
  - maptools
  - covr

before_install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then 
      brew install llvm;
      export PATH="/usr/local/opt/llvm/bin:$PATH";
    fi
  
after_success:
  - Rscript -e 'covr::codecov()'

# notifications:
#   email:
#     - kongdd.sysu@gmail.com
#     on_success: always # default: change
#     on_failure: always # default: always
